//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyCompanyAttribute("")]
[assembly: AssemblyProductAttribute("FlubuExample")]
[assembly: AssemblyCopyrightAttribute("")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyFileVersionAttribute("1.1.0.0")]
[assembly: ComVisible(false)]
[assembly: AssemblyInformationalVersionAttribute("1.1")]
[assembly: AssemblyVersionAttribute("1.1")]
[assembly: AssemblyConfigurationAttribute("Release")]
